# Generated by Django 2.2.16 on 2021-10-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20211004_1736'),
    ]

    operations = []
