# Generated by Django 2.2.16 on 2021-10-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20211004_1801'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
